services:
  api:
    build: .
    container_name: cosmetic_api
    env_file:
      - .env.docker
    depends_on:
      - mongodb
    ports:
      - "8080:8000"
    volumes:
      - ./static:/app/static
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: cosmetic_shop_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    restart: unless-stopped

volumes:
  mongo_data:
